# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'T:\Tools\eric6-18.10\Scratch\ui\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):

    from _workbench import configs
    config_obj = configs.configs()
    global fileName
    fileName = None
    global startID
    startID_str = config_obj.read_config('Last_Setup', 'startID')
    startID = startID_str
    global culture
    culture = config_obj.read_config('Last_Setup', 'culture')
    global religion
    religion = config_obj.read_config('Last_Setup', 'religion')
    global is_tribal
    is_tribal_str = config_obj.read_config('Last_Setup', 'is_tribal')
    if is_tribal_str in ['true']:
        is_tribal = True
    else:
        is_tribal = False
    global terrain
    terrain = config_obj.read_config('Last_Setup', 'terrain')
    global rgb_basis
    rgb_basis_listl = config_obj.read_config('Last_Setup', 'rgb_basis')
    import ast
    rgb_basis = ast.literal_eval(rgb_basis_listl)
    global rgb_basis_r
    rgb_basis_r = rgb_basis[0]
    global rgb_basis_g
    rgb_basis_g = rgb_basis[1]
    global rgb_basis_b
    rgb_basis_b = rgb_basis[2]
    global flag_removal
    flag_removal = False

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(247, 338)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setWindowTitle("Province Set-Upper")
        MainWindow.setAutoFillBackground(True)
        MainWindow.setAnimated(True)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setEnabled(True)
        self.centralWidget.setAutoFillBackground(True)
        self.centralWidget.setObjectName("centralWidget")
        self.widget = QtWidgets.QWidget(self.centralWidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 225, 280))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_load = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_load.sizePolicy().hasHeightForWidth())
        self.pushButton_load.setSizePolicy(sizePolicy)
        self.pushButton_load.setMaximumSize(QtCore.QSize(88, 23))
        self.pushButton_load.setObjectName("pushButton_load")
        self.horizontalLayout_6.addWidget(self.pushButton_load)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_startid = QtWidgets.QLabel(self.widget)
        self.label_startid.setObjectName("label_startid")
        self.horizontalLayout_5.addWidget(self.label_startid)
        self.lineEdit_startID = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_startID.sizePolicy().hasHeightForWidth())
        self.lineEdit_startID.setSizePolicy(sizePolicy)
        self.lineEdit_startID.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhPreferNumbers)
        self.lineEdit_startID.setText(startID)
        self.lineEdit_startID.setPlaceholderText(startID)
        self.lineEdit_startID.setObjectName("lineEdit_startID")
        self.horizontalLayout_5.addWidget(self.lineEdit_startID)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_religion = QtWidgets.QLabel(self.widget)
        self.label_religion.setObjectName("label_religion")
        self.horizontalLayout.addWidget(self.label_religion)
        self.lineEdit_religion = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_religion.sizePolicy().hasHeightForWidth())
        self.lineEdit_religion.setSizePolicy(sizePolicy)
        self.lineEdit_religion.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhLatinOnly|QtCore.Qt.ImhPreferNumbers)
        self.lineEdit_religion.setText(religion)
        self.lineEdit_religion.setObjectName("lineEdit_religion")
        self.horizontalLayout.addWidget(self.lineEdit_religion)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_culture = QtWidgets.QLabel(self.widget)
        self.label_culture.setObjectName("label_culture")
        self.horizontalLayout_2.addWidget(self.label_culture)
        self.lineEdit_culture = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_culture.sizePolicy().hasHeightForWidth())
        self.lineEdit_culture.setSizePolicy(sizePolicy)
        self.lineEdit_culture.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhLatinOnly|QtCore.Qt.ImhPreferNumbers)
        self.lineEdit_culture.setText(culture)
        self.lineEdit_culture.setClearButtonEnabled(False)
        self.lineEdit_culture.setObjectName("lineEdit_culture")
        self.horizontalLayout_2.addWidget(self.lineEdit_culture)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_terrain = QtWidgets.QLabel(self.widget)
        self.label_terrain.setObjectName("label_terrain")
        self.horizontalLayout_4.addWidget(self.label_terrain)
        self.lineEdi_terrain = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdi_terrain.sizePolicy().hasHeightForWidth())
        self.lineEdi_terrain.setSizePolicy(sizePolicy)
        self.lineEdi_terrain.setInputMethodHints(QtCore.Qt.ImhLatinOnly)
        self.lineEdi_terrain.setText(terrain)
        self.lineEdi_terrain.setObjectName("lineEdi_terrain")
        self.horizontalLayout_4.addWidget(self.lineEdi_terrain)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_rgbbase = QtWidgets.QLabel(self.widget)
        self.label_rgbbase.setObjectName("label_rgbbase")
        self.horizontalLayout_3.addWidget(self.label_rgbbase)
        self.spinBox_r = QtWidgets.QSpinBox(self.widget)
        self.spinBox_r.setMaximum(255)
        self.spinBox_r.setProperty("value", rgb_basis_r)
        self.spinBox_r.setObjectName("spinBox_r")
        self.horizontalLayout_3.addWidget(self.spinBox_r)
        self.spinBox_g = QtWidgets.QSpinBox(self.widget)
        self.spinBox_g.setMaximum(255)
        self.spinBox_g.setProperty("value", rgb_basis_g)
        self.spinBox_g.setObjectName("spinBox_g")
        self.horizontalLayout_3.addWidget(self.spinBox_g)
        self.spinBox_b = QtWidgets.QSpinBox(self.widget)
        self.spinBox_b.setMaximum(255)
        self.spinBox_b.setProperty("value", rgb_basis_b)
        self.spinBox_b.setObjectName("spinBox_b")
        self.horizontalLayout_3.addWidget(self.spinBox_b)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.line_3 = QtWidgets.QFrame(self.widget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.checkBox_flagremoval = QtWidgets.QCheckBox(self.widget)
        self.checkBox_flagremoval.setObjectName("checkBox_flagremoval")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.checkBox_flagremoval)
        self.checkBox_isTribal = QtWidgets.QCheckBox(self.widget)
        self.checkBox_isTribal.setObjectName("checkBox_isTribal")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.checkBox_isTribal)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_tepledist = QtWidgets.QLabel(self.widget)
        self.label_tepledist.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_tepledist.setWordWrap(False)
        self.label_tepledist.setObjectName("label_tepledist")
        self.horizontalLayout_8.addWidget(self.label_tepledist)
        self.spinBox_templedist = QtWidgets.QSpinBox(self.widget)
        self.spinBox_templedist.setMaximum(100)
        self.spinBox_templedist.setObjectName("spinBox_templedist")
        self.horizontalLayout_8.addWidget(self.spinBox_templedist)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_8)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.line_2 = QtWidgets.QFrame(self.widget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_write = QtWidgets.QPushButton(self.widget)
        self.pushButton_write.setEnabled(True)
        self.pushButton_write.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_write.setObjectName("pushButton_write")
        self.horizontalLayout_7.addWidget(self.pushButton_write)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 247, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionConfig = QtWidgets.QAction(MainWindow)
        self.actionConfig.setObjectName("actionConfig")
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionHelp)
        self.menuFile.addAction(self.actionConfig)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.label_startid.setBuddy(self.lineEdit_startID)
        self.label_religion.setBuddy(self.lineEdit_religion)
        self.label_culture.setBuddy(self.lineEdit_culture)
        self.label_terrain.setBuddy(self.lineEdi_terrain)
        self.label_rgbbase.setBuddy(self.spinBox_r)
        self.label_tepledist.setBuddy(self.spinBox_templedist)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.pushButton_load, self.lineEdit_startID)
        MainWindow.setTabOrder(self.lineEdit_startID, self.lineEdit_religion)
        MainWindow.setTabOrder(self.lineEdit_religion, self.lineEdit_culture)
        MainWindow.setTabOrder(self.lineEdit_culture, self.lineEdi_terrain)
        MainWindow.setTabOrder(self.lineEdi_terrain, self.spinBox_r)
        MainWindow.setTabOrder(self.spinBox_r, self.spinBox_g)
        MainWindow.setTabOrder(self.spinBox_g, self.spinBox_b)
        MainWindow.setTabOrder(self.spinBox_b, self.checkBox_flagremoval)
        MainWindow.setTabOrder(self.checkBox_flagremoval, self.checkBox_isTribal)
        MainWindow.setTabOrder(self.checkBox_isTribal, self.spinBox_templedist)
        MainWindow.setTabOrder(self.spinBox_templedist, self.pushButton_write)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.pushButton_load.setToolTip(_translate("MainWindow", "Load the .csv file"))
        self.pushButton_load.setText(_translate("MainWindow", "Load"))
        self.label_startid.setText(_translate("MainWindow", "Start ID:"))
        self.lineEdit_startID.setToolTip(_translate("MainWindow", "<html><head/><body><p>The province ID of the first province.</p></body></html>"))
        self.label_religion.setText(_translate("MainWindow", "Religion:"))
        self.lineEdit_religion.setToolTip(_translate("MainWindow", "<html><head/><body><p>The religion of all provinces.</p></body></html>"))
        self.lineEdit_religion.setPlaceholderText(_translate("MainWindow", religion))
        self.label_culture.setText(_translate("MainWindow", "Culture:"))
        self.lineEdit_culture.setToolTip(_translate("MainWindow", "<html><head/><body><p>The culture of all provinces.</p></body></html>"))
        self.lineEdit_culture.setPlaceholderText(_translate("MainWindow", culture))
        self.label_terrain.setText(_translate("MainWindow", "Terrain:"))
        self.lineEdi_terrain.setAccessibleDescription(_translate("MainWindow", "The terrain of the provinces"))
        self.lineEdi_terrain.setPlaceholderText(_translate("MainWindow", terrain))
        self.label_rgbbase.setText(_translate("MainWindow", "RGB Base:"))
        self.checkBox_flagremoval.setToolTip(_translate("MainWindow", "<html><head/><body><p>Put used flag into a seperate folder, filtering them out</p></body></html>"))
        self.checkBox_flagremoval.setText(_translate("MainWindow", "Flag Removal"))
        self.checkBox_isTribal.setAccessibleDescription(_translate("MainWindow", "Check if the county capital is tribal."))
        self.checkBox_isTribal.setText(_translate("MainWindow", "Is Tribal"))
        self.label_tepledist.setText(_translate("MainWindow", "Temple Dist.:"))
        self.spinBox_templedist.setToolTip(_translate("MainWindow", "<html><head/><body><p>Chance that a temple will be added to the tribal holding.</p></body></html>"))
        self.pushButton_write.setToolTip(_translate("MainWindow", "Write the files."))
        self.pushButton_write.setText(_translate("MainWindow", "Write"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionConfig.setText(_translate("MainWindow", "Config"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

