# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\Paradox Interactive\Crusader Kings II\Modding\Province Set-Upper Eric\ui\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(229, 340)
        MainWindow.setMouseTracking(False)
        MainWindow.setAutoFillBackground(False)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.pushButton_load = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_load.sizePolicy().hasHeightForWidth())
        self.pushButton_load.setSizePolicy(sizePolicy)
        self.pushButton_load.setMaximumSize(QtCore.QSize(88, 23))
        self.pushButton_load.setObjectName("pushButton_load")
        self.horizontalLayout_6.addWidget(self.pushButton_load)
        spacerItem1 = QtWidgets.QSpacerItem(250, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.line = QtWidgets.QFrame(self.centralWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.centralWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.lineEdit_startID = QtWidgets.QLineEdit(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_startID.sizePolicy().hasHeightForWidth())
        self.lineEdit_startID.setSizePolicy(sizePolicy)
        self.lineEdit_startID.setText("")
        self.lineEdit_startID.setObjectName("lineEdit_startID")
        self.horizontalLayout_5.addWidget(self.lineEdit_startID)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit_religion = QtWidgets.QLineEdit(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_religion.sizePolicy().hasHeightForWidth())
        self.lineEdit_religion.setSizePolicy(sizePolicy)
        self.lineEdit_religion.setText("")
        self.lineEdit_religion.setObjectName("lineEdit_religion")
        self.horizontalLayout.addWidget(self.lineEdit_religion)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit_culture = QtWidgets.QLineEdit(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_culture.sizePolicy().hasHeightForWidth())
        self.lineEdit_culture.setSizePolicy(sizePolicy)
        self.lineEdit_culture.setText("")
        self.lineEdit_culture.setClearButtonEnabled(False)
        self.lineEdit_culture.setObjectName("lineEdit_culture")
        self.horizontalLayout_2.addWidget(self.lineEdit_culture)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem5 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.checkBox_isTribal = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_isTribal.setObjectName("checkBox_isTribal")
        self.horizontalLayout_8.addWidget(self.checkBox_isTribal)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.lineEdi_terrain = QtWidgets.QLineEdit(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdi_terrain.sizePolicy().hasHeightForWidth())
        self.lineEdi_terrain.setSizePolicy(sizePolicy)
        self.lineEdi_terrain.setText("")
        self.lineEdi_terrain.setObjectName("lineEdi_terrain")
        self.horizontalLayout_4.addWidget(self.lineEdi_terrain)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.spinBox_r = QtWidgets.QSpinBox(self.centralWidget)
        self.spinBox_r.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinBox_r.setMaximum(255)
        self.spinBox_r.setProperty("value", 255)
        self.spinBox_r.setObjectName("spinBox_r")
        self.horizontalLayout_3.addWidget(self.spinBox_r)
        self.spinBox_g = QtWidgets.QSpinBox(self.centralWidget)
        self.spinBox_g.setMaximum(255)
        self.spinBox_g.setProperty("value", 105)
        self.spinBox_g.setObjectName("spinBox_g")
        self.horizontalLayout_3.addWidget(self.spinBox_g)
        self.spinBox_b = QtWidgets.QSpinBox(self.centralWidget)
        self.spinBox_b.setMaximum(255)
        self.spinBox_b.setObjectName("spinBox_b")
        self.horizontalLayout_3.addWidget(self.spinBox_b)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem8)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.line_2 = QtWidgets.QFrame(self.centralWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        spacerItem9 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem9)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem10 = QtWidgets.QSpacerItem(88, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem10)
        self.pushButton_write = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_write.setEnabled(True)
        self.pushButton_write.setObjectName("pushButton_write")
        self.horizontalLayout_7.addWidget(self.pushButton_write)
        spacerItem11 = QtWidgets.QSpacerItem(88, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem11)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 229, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionHelp)
        self.menuFile.addAction(self.actionQuit)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.label_5.setBuddy(self.lineEdit_startID)
        self.label_2.setBuddy(self.lineEdit_religion)
        self.label.setBuddy(self.lineEdit_culture)
        self.label_4.setBuddy(self.lineEdi_terrain)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.pushButton_load, self.lineEdit_startID)
        MainWindow.setTabOrder(self.lineEdit_startID, self.lineEdit_religion)
        MainWindow.setTabOrder(self.lineEdit_religion, self.lineEdit_culture)
        MainWindow.setTabOrder(self.lineEdit_culture, self.checkBox_isTribal)
        MainWindow.setTabOrder(self.checkBox_isTribal, self.lineEdi_terrain)
        MainWindow.setTabOrder(self.lineEdi_terrain, self.pushButton_write)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Province Set-Upper"))
        self.pushButton_load.setText(_translate("MainWindow", "Load"))
        self.label_5.setText(_translate("MainWindow", "Start ID:"))
        self.lineEdit_startID.setToolTip(_translate("MainWindow", "<html><head/><body><p>The default culture of all provinces</p></body></html>"))
        self.lineEdit_startID.setPlaceholderText(_translate("MainWindow", "16"))
        self.label_2.setText(_translate("MainWindow", "Religion:"))
        self.lineEdit_religion.setToolTip(_translate("MainWindow", "<html><head/><body><p>The default culture of all provinces</p></body></html>"))
        self.lineEdit_religion.setPlaceholderText(_translate("MainWindow", "Catholic"))
        self.label.setText(_translate("MainWindow", "Culture:"))
        self.lineEdit_culture.setToolTip(_translate("MainWindow", "<html><head/><body><p>The default culture of all provinces</p></body></html>"))
        self.lineEdit_culture.setPlaceholderText(_translate("MainWindow", "Norse"))
        self.checkBox_isTribal.setText(_translate("MainWindow", "Is Tribal"))
        self.label_4.setText(_translate("MainWindow", "Terrain:"))
        self.lineEdi_terrain.setPlaceholderText(_translate("MainWindow", "Plains"))
        self.label_3.setText(_translate("MainWindow", "RGB Base:"))
        self.pushButton_write.setText(_translate("MainWindow", "Write"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

